defaults:
  - _self_
  - backbone: dinov2_small


model_name: dinowm_pusht_fixed
history_size: 3
num_preds: 1
proprio_dim: 4
action_dim: 2
backbone_only: true # whether to use the full model or just the vision backbone for encoding
encoding: # key: target dim
  proprio: 10
  action: 10
