defaults:
  - _self_
  - world_model: pyro

cache_dir: null

device: cuda
seed: 42

image_size: 224
patch_size: 16

dimensionality_reduction: tsne

# Define environment to visualize (and potential variations)
env:
  env_name: swm/TwoRoom-v0
  history_size: 1
  frame_skip: 1
  grid_size: 20  # number of states per dimension for visualization
  variations:
    - variation:
        fields: null # default environment
        values: null
    - variation:
        fields: ["background.color"] # vary background color
        values: [[0.1, 0.2, 0.3]]
