defaults:
  - world_model@datasets.pusht.world_model: iql
  - _self_

cache_dir: null
device: cuda
seed: 42

image_size: 224
patch_size: 14

# ===============================
# Dataset / Environment definitions
# ===============================
datasets:
  pusht:
    training_dataset: pusht_expert_train  # dataset used during training for preprocessing stats
    env:
      env_name: swm/PushT-v1
      history_size: 3
      frame_skip: 1
      grid_size: 20
      default_variation: ["agent.start_position"]
      variations:
        - variation:
            fields: null
            values: null
    world_model:
      model_name: iql10_policy_epoch_9
