defaults:
  - _self_

model_name: dinowm_pusht_fixed
cache_dir: null

device: cuda
seed: 42

env:
  env_name: swm/PushT-v1
  history_size: 1
  frame_skip: 1
  grid_size: 10  # number of states per dimension for visualization
  variations:
    - variation: null # default environment
    - variation: ["background.color"] # vary background color

image_size: 224
patch_size: 16

n_steps: ${eval:'${dinowm.num_preds} + ${dinowm.history_size}'}
frameskip: 5

dinowm:
  history_size: 3
  num_preds: 1
  proprio_dim: 4
  action_dim: 2
  encoding: # key: target dim
    proprio: 10
    action: 10
